[project]
name = "honey-gnn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.0",
    "scipy>=1.16.1",
    "torch-geometric>=2.6.1",
    "torch==2.7.1+cu128",
    "scipy==1.16.1",
    "ipykernel==6.30.0",
    "transformers>=4.54.0",
    "hf-xet>=1.1.5",
    "scikit-learn>=1.7.1",
    "matplotlib>=3.10.3",
    "emoji==1.4.1",
    "seaborn>=0.13.2",
    "streamlit>=1.47.1",
    "plotly>=6.2.0",
]

[tool.uv.sources]
torch = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu128"
explicit=true
